// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnDGVJD61Sl4n3gTpsctr6dA7H7o3evTc',
    appId: '1:764137362860:web:fd7fe3a04b1d0761831609',
    messagingSenderId: '764137362860',
    projectId: 'waveact-e419c',
    authDomain: 'waveact-e419c.firebaseapp.com',
    storageBucket: 'waveact-e419c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA0NS71lBtAeUa7MdgfKzflnmTBuxT-hE',
    appId: '1:764137362860:android:be9414f9b0d37410831609',
    messagingSenderId: '764137362860',
    projectId: 'waveact-e419c',
    storageBucket: 'waveact-e419c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmV2DzpJR7QMiOzNlgTfLkGKfkq01vQc0',
    appId: '1:764137362860:ios:b421b1303e3f0215831609',
    messagingSenderId: '764137362860',
    projectId: 'waveact-e419c',
    storageBucket: 'waveact-e419c.firebasestorage.app',
    iosBundleId: 'com.example.gmi',
  );
}
